import axios from "axios";

//AQUI FICA A INSTÂNCIA DO AXIOS. UMA CONFIGURAÇÃO BASE QUE UTILIZAMOS PARA CONSTRUIR AS ROTAS
//NOTE QUE TEMOS DUAS LINHAS DIFERENTES. UMA LINHA CHAMADA
//process.env.EXPO_PUBLIC_MOVIE_URL
//process.env.EXPO_PUBLIC_API_KEY
//ESSAS SÃO NOSSAS VARIÁVEIS DE AMBIENTE. SÃO INFORMAÇÕES SIGILOSAS E QUE NÃO PODEM FICAR VISIVEIS PARA QUE OUTRAS PESSOAS POSSAM UTILIZAR
//ISSO É QUESTÃO DE SEGURANÇA DA NOSSA APLICAÇAO. ESSAS VARIÁVEIS FICAM EM UM ARQUIVO CHAMADO .env, NA RAIZ DO PROJETO.
//CRIE UM ARQUIVO CHAMADO .env E CRIE ESSAS DUAS VARIÁVEIS
//EXEMPLO:
//EXPO_PUBLIC_MOVIE_URL="https://endereco-base-da-api"
//EXPO_PUBLIC_API_KEY=chave-da-api-gerada-pelo-site
//A SUA CHAVE É ÚNICA, NÃO MOSTRE PARA NINGUÉM.
//ESSE ARQUIVO .env NÃO SOBE PARA O GITHUB, FICA APENAS NO SEU COMPUTADOR.

//EXPORTE A API
export const api = axios.create({
  baseURL: process.env.EXPO_PUBLIC_MOVIE_URL,
  timeout: 5000,
  params: {
    api_key: process.env.EXPO_PUBLIC_API_KEY,
    language: "pt-BR",
  },
});
